name: tenantflow
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI and Icons
  cupertino_icons: ^1.0.8

  # Firebase Dependencies
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1

  # Google Sign-In
  google_sign_in: ^6.2.2

  # Apple Sign-In
  sign_in_with_apple: ^6.1.0

  # Package to change app package name
  change_app_package_name: ^1.5.0

  # State Management
  provider: ^6.1.2

  # Shared Preferences
  shared_preferences: ^2.2.0

  # New Dependencies
  image_picker: ^1.1.2  # For picking images
  url_launcher: ^6.3.0  # For launching email apps
  http: ^1.2.2  # For API calls
  firebase_dynamic_links: ^6.1.4
  google_generative_ai: ^0.4.6
  flutter_markdown: ^0.7.7
  razorpay_web: ^2.0.2
  firebase_storage: ^12.4.5
  image_picker_web: ^4.0.0
  universal_html: ^2.2.4
  cloud_firestore: ^5.6.6
  # google_translator: ^1.0.0
  translator: ^1.0.3+1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/images/